apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j65808v84-java-quarkus
  janus-idp.io/tekton: j65808v84-java-quarkus
  backstage.io/kubernetes-id: j65808v84-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j65808v84-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
